USE_CAMERA_STUB := true

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := 3475
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

#To be reviewed
TARGET_BOOTLOADER_BOARD_NAME := EXYNOS3475

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --dt device/samsung/j2lte/dt.img
#Check all above this

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 13631488 # 13312 * 1024 mmcblk0p10
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 15728640 # 15360 * 1024 mmcblk0p11
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2415919104 # 2359296 * 1024 mmcblk0p20
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4970250240 # 4853760 * 1024 mmcblk0p23
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/samsung/j2lte/kernel

# TWRP
TW_THEME := portrait_hdpi
TARGET_RECOVERY_FSTAB := device/samsung/j2lte/twrp.fstab
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"
DEVICE_RESOLUTION := 540x960
TW_DEFAULT_EXTERNAL_STORAGE := true
TW_FLASH_FROM_STORAGE := true
TARGET_USE_CUSTOM_LUN_FILE_PATH := /sys/class/android_usb/android0/f_mass_storage/lun%d/file
TW_NO_REBOOT_BOOTLOADER := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_10x18.h\"
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true



# don't take forever to wipe
BOARD_SUPPRESS_SECURE_ERASE := true
COMMON_GLOBAL_CFLAGS += -DNO_SECURE_DISCARD
