USE_CAMERA_STUB := true

# inherit from the proprietary version
#include vendor/samsung/j2lte/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := 3475
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

#To be reviewed
TARGET_BOOTLOADER_BOARD_NAME := EXYNOS3475

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
#Check all above this

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 13631488 # 13312 * 1024 mmcblk0p10
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 15728640 # 15360 * 1024 mmcblk0p11
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2415919104 # 2359296 * 1024 mmcblk0p20
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4970250240 # 4853760 * 1024 mmcblk0p23
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/samsung/j2lte/kernel
RECOVERY_GRAPHICS_USE_LINELENGTH := true 
TARGET_RECOVERY_PIXEL_FORMAT := "BRGA_8888"

RECOVERY_SDCARD_ON_DATA := true

# don't take forever to wipe
BOARD_SUPPRESS_SECURE_ERASE := true
COMMON_GLOBAL_CFLAGS += -DNO_SECURE_DISCAR

# TWRP
TW_THEME := portrait_hdpi
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_INCLUDE_CRYPTO := true
TW_SCREEN_BLANK_ON_BOOT := true